# Generated by Django 5.1.5 on 2025-01-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'CLIENT'), ('employee', 'EMPLOYEE'), ('customer representative', 'CUSTOMER REPRESENTATIVE')], default='user', max_length=100),
        ),
    ]
