# Generated by Django 5.1.5 on 2025-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'CLIENT'), ('employee', 'EMPLOYEE'), ('customer representative', 'CUSTOMER REPRESENTATIVE')], default='client', max_length=100),
        ),
    ]
