# Generated by Django 5.1.5 on 2025-02-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'CLIENT'), ('employee', 'EMPLOYEE'), ('customer representative', 'CUSTOMER REPRESENTATIVE')], max_length=100),
        ),
    ]
